#ifndef ODRIVE_ENUMS_H
#define ODRIVE_ENUMS_H
#include <string>

#define AXIS_STATE_UNDEFINED 0
#define AXIS_STATE_IDLE 1
#define AXIS_STATE_STARTUP_SEQUENCE 2
#define AXIS_STATE_FULL_CALIBRATION_SEQUENCE 3
#define AXIS_STATE_MOTOR_CALIBRATION 4
#define AXIS_STATE_ENCODER_INDEX_SEARCH 6
#define AXIS_STATE_ENCODER_OFFSET_CALIBRATION 7
#define AXIS_STATE_CLOSED_LOOP_CONTROL 8
#define AXIS_STATE_LOCKIN_SPIN 9
#define AXIS_STATE_ENCODER_DIR_FIND 10
#define AXIS_STATE_HOMING 11
#define AXIS_STATE_ENCODER_HALL_POLARITY_CALIBRATION 12
#define AXIS_STATE_ENCODER_HALL_PHASE_CALIBRATION 13


#endif
